**Problem 1**

Import Numpy as np

In [1]:
import numpy as np


**Problem 2**

Create a 1D array of numbers from 0 to 9.

In [41]:
array1=np.arange(0,10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


**Problem 3**

Create a 3×3 numpy array of all True’s.

In [5]:
array_true=np.full([3,3],True)
print(array_true)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Problem 4**

Extract all odd numbers from arr.

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

**Problem 5**

Replace all odd numbers in arr with -1.

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Problem 6**

Convert a 1D array to a 2D array with 2 rows.

In [14]:
arr1=np.arange(10)
print(arr1.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


**Problem 7** 

Stack arrays a and b vertically.

In [21]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**Problem 8**

Stack the arrays a and b horizontally.

In [22]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

**Problem 9**

Get the common items between a and b.

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

**Problem 10**

From array a remove all items present in array b

In [31]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c=np.intersect1d(a,b)
new_array = np.setdiff1d(a, b)
print(new_array)

[1 2 3 4]


**Problem 11**

Get the positions where elements of a and b match

In [40]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c,ind_a,ind_b=np.intersect1d(a,b,return_indices=True)
print(ind_a,ind_b)

[1 5] [1 5]


**Problem 12** 

Get all items between 5 and 10 from a.

In [48]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[np.logical_and(a>5 , a<10)]

array([6, 9])

**Problem 13**

Swap columns 1 and 2 in the array arr.

In [60]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [61]:
arr = np.arange(9).reshape(3,3)

arr[:, [1,2]]=arr[:,[2,1]]
print(arr)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


**Problem 14**

Swap rows 1 and 2 in the array arr.

In [62]:
arr = np.arange(9).reshape(3,3)
arr[[1,2],:]=arr[[2,1],:]
print(arr)

[[0 1 2]
 [6 7 8]
 [3 4 5]]


**Problem 15**

Reverse the rows of a 2D array arr.

In [81]:
arr = np.arange(9).reshape(3,3)
print(arr)
#arr[[0,2],:]=arr[[2,0],:]

#print(arr)
np.flip(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

**Problem 16**

Reverse the columns of a 2D array arr.

In [67]:
arr = np.arange(9).reshape(3,3)
arr[:,[0,2]]=arr[:,[2,0]]
print(arr)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


**Problem 17**

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [83]:
#np.random.randint(5,10,(5,3))
rand_arr=np.random.uniform(5,10,[5,3])
print(rand_arr)

[[9.112 7.065 9.901]
 [8.344 7.591 8.581]
 [7.471 5.908 8.711]
 [6.892 5.97  9.625]
 [5.016 6.368 8.064]]


**Problem 18**

Print or show only 3 decimal places of the numpy array rand_arr.

In [84]:
np.set_printoptions(precision=3)
print(rand_arr)

[[9.112 7.065 9.901]
 [8.344 7.591 8.581]
 [7.471 5.908 8.711]
 [6.892 5.97  9.625]
 [5.016 6.368 8.064]]


In [53]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10], [11, 12]])
print(a,b.T)
d = np.dot(a, b.T)
print(d)


[[1 2]
 [3 4]
 [5 6]] [[ 7  9 11]
 [ 8 10 12]]
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]
